name: torogi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  drift: ^2.26.1
  isar: ^3.1.0+1
  app_links: ^6.4.0

  equatable: ^2.0.7
  flutter_rating_bar: ^4.0.1
  simple_animations: ^5.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  fluttertoast: ^8.2.12
  connectivity_plus: ^6.1.4

  get_it: ^8.0.3
  go_router: ^15.2.3
  shared_preferences: ^2.5.3
  google_mobile_ads: ^6.0.0
  image_picker: ^1.1.2
  supabase_flutter: ^2.8.4
  fade_shimmer: ^2.4.0
  timeago: ^3.7.1
  logging:
  google_fonts: ^6.2.1
  sqlite3: ^2.7.6
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.7.0
  webview_flutter_wkwebview: ^3.22.0
  sqlite3_flutter_libs: ^0.5.34
  path_provider: ^2.1.5
  drift_dev: ^2.27.0
  build_runner: ^2.5.4
  uuid: ^4.5.1
  cached_network_image: ^3.4.1
  file_picker: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo_icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/logo.png
    - assets/logo_icon.png
    - assets/logo_icon.png
